### ISSUE TITLE
Prise en compte des coordonnées géographiques dans les données

### ISSUE THREAD

**Issue by trasher** [Anaphore/bach#12]

**Comment by chapseb** [comment]
Je suis en train de faire la fonctionnalité, j'arrive à faire les insert et update dans la base de données. Cependant, j'essaye de faire des requêtes préparées comme pour l'enregistrement des documents. Mais, je n'arrive pas à comprendre comment fonctionne la fonction _storeDocument (dans le publishCommand.php), plus précisement les statements et surtout comment dans le else (lorsque le statement existe), cela peut lancer un insert (ou update) avec les bonnes valeurs ?

**Comment by chapseb** [comment]
C'est bon, je viens de comprendre le principe, il fallait juste que ça fasse 'tilt'.
