### ISSUE TITLE
Recherche sur les dates

### ISSUE THREAD

**Issue by trasher** [Anaphore/bach#30]
Actuellement, lorsque l'on cherche une date dans les documents d'archives, on compare l'intervalle recherché avec la date de début calculée lors de la publication.

Les composants qui sont références par une période de dates ne seront potentiellement pas trouvés (ie. un composant ayant pour dates extrêmes 1800/1900 ne sortira pas lors d'une recherche sur l'année 1850).

Pour que tout fonctionne correctement, la recherche devrait s'effectuer sur l'intervalle (ce qui impllique probablement que le ticket #29 soit corrigé d'abord).

Ceci étant dit, il faudrait savoir si le jeu en vaut la chandelle, ça risque d'être un peu compliqué à résoudre, et je ne sais pas si ça concerne les composants de bas niveau ou pas.

**Comment by chapseb** [comment]
Une première partie de correctif est dans le commit 9f01488dc807ab82169e5f6badb64bca2d803cd7 .
Il faudra améliorer l'affichage car le fait que l'histogramme et la facette de dates (qui se servent du champ solr cDateBegin) soient désynchronisés des résultats, peut être destabilisant pour l'utilsateur.
